services:
    - docker

before_script:
    - echo "Logging into Docker Hub"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

matrix:
    include:
        - name: "Exercice 1 - Travis"
          script:
            - git checkout tags/exercice-1
            - docker build -t nothing:exercice-1-travis .
            - docker push rodolpheh/docker-lessons:exercice-1-travis
        - name: "Exercice 2 - Travis"
          script:
            - git checkout tags/exercice-2
            - docker build -t nothing:exercice-2-travis .
            - docker push rodolpheh/docker-lessons:exercice-2-travis
